export enum QuestionType {
    GRADUSHKA = 'GRADUSHKA',
    SILNI_VETROVE = 'SILNI_VETROVE',
    PROLIVEN_DAJD_NAVODNENIE = 'PROLIVEN_DAJD_NAVODNENIE',
    OGAN = 'OGAN',
    OSLANQVANE = 'OSLANQVANE',
    KISHA = 'KISHA',
    IZMRAZVANE = 'IZMRAZVANE',
    IZTEGLQNE = 'IZTEGLQNE'
}